```yaml
name: Publish tplink_sms to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v0.1.0, v0.1.1, etc.

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi  # Optional: requires manual approval
    permissions:
      id-token: write  # Required for Trusted Publishing

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for version tagging

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Use latest Python 3.x

      # Install build dependencies
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Build the package
      - name: Build package
        run: python -m build

      # Publish to TestPyPI (optional, for testing)
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true  # Skip if version exists
          packages-dir: dist/

      # Publish to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
```